name: TourGuide CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install local dependencies
      run: |
        mvn install:install-file -Dfile=TourGuide/libs/gpsUtil-1.0.0.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=TourGuide/libs/tripPricer-1.0.0.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=TourGuide/libs/rewardCentral-1.0.0.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
    
    - name: Build with Maven
      run: |
        cd TourGuide
        mvn -B package -Dtest=!com.openclassrooms.tourguide.TestPerformance
